name: moralization
channels:
  - conda-forge

dependencies:
  - python
  - numpy 
  - pandas 
  - matplotlib 
  - seaborn 
  - click
  - importlib_metadata
  - openpyxl
  - ipywidgets
  - pip:
    - dkpro-cassis
    - pytest-cov
    - pytest
    - spacy
    - spacy_span_analyzer
    - textacy
    - spacy-huggingface-hub